name: Cargo Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: VylFs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse3-dev mold

      - name: Setup Rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Set RUSTFLAGS for Mold linker
        run: echo "RUSTFLAGS=-C linker=mold" >> $GITHUB_ENV

      - name: Cargo build
        run: cargo build --verbose

      - name: Cargo test
        run: cargo test --verbose
